### ISSUE TITLE
Curseforge app mod visibility

### ISSUE THREAD

**Issue by SpinnyBoiii** [jellysquid3/Lithium#245]
Affected Versions:
Lithium mc1.16.5-0.6.6
Lithium mc1.16.5-0.6.1
I feel like this might be an issue with the new CurseFabric rather than the mod versions, but these versions are for some reason only visible on a forge profile on the curseforge app.

**Comment by amnotbananaama** [comment]
It looks like [those](https://www.curseforge.com/minecraft/mc-mods/lithium/files/3344974) files are not marked as supporting the Fabric modloader. I'm not familiar with the CurseForge UI, but I would imagine it's possible to edit the file and add that

**Comment by 2No2Name** [comment]
I set the supported mod loader to fabric. Is it fixed now?

**Comment by SpinnyBoiii** [comment]
> I set the supported mod loader to fabric. Is it fixed now?

will take a bit to check, the app seems to have 2-3h delay to the site

**Comment by SpinnyBoiii** [comment]
![image](https://user-images.githubusercontent.com/49210394/122488423-bb2de000-cfdd-11eb-9212-a3a985949462.png)
still not visible(warning sign is because I've got Lithium mc1.16.5-0.6.6, which it cant see, it will still function as it's supposed to)

**Comment by SpinnyBoiii** [comment]
![image](https://user-images.githubusercontent.com/49210394/122492238-afdeb280-cfe5-11eb-9b0d-954693569f88.png)
for some reason still a warning, but its visible

**Comment by LucilleTea** [comment]
0.7.2 needs to be marked as fabric compatible too.

**Comment by 2No2Name** [comment]
This should be fixed now, if not it is probably not an issue we can fix on lithium's side
