### ISSUE TITLE
Incorrect hopper behaviour in Lithium 0.9.0 dev build

### ISSUE THREAD

**Issue by kikugie** [jellysquid3/Lithium#395]
Tested with build https://github.com/CaffeineMC/lithium-fabric/actions/runs/3038168288  

Issue occurred when using [Set Based Unloader Array](https://discord.com/channels/748542142347083868/749136547755851857/983793044404985896). At the input handler shulker box arrives too late for recombining and drains a filter item.  
![2022-09-18_20 58 12](https://user-images.githubusercontent.com/50152507/190924445-b3bed8c6-b836-43d7-8316-f1863830932b.png)
![2022-09-18_21 09 42](https://user-images.githubusercontent.com/50152507/190924450-69f98ce4-3bc2-42bd-be86-8fd5142a99ec.png)

How to reproduce:  
- Download any version of the set based unloader
- Input shulker box with any stackable items
- Box is spit out to the side instead of being processed further
- Do the same steps without the mod to observe correct behaviour

**Comment by 2No2Name** [comment]
Thank you for reporting this. I think this should be fixed in the latest commit which I just pushed.

**Comment by kikugie** [comment]
Tested build https://github.com/CaffeineMC/lithium-fabric/actions/runs/3078524315  
That issue is still not fixed.

**Comment by 2No2Name** [comment]
Thanks for testing again, fixed it now and also tested the setup. Issue was that powered hoppers started to sleep and then while sleeping started to sleep again, which made them not wake up properly anymore
